### ISSUE TITLE
How to ignore blocks of code

### ISSUE THREAD

**Issue by eddiemonge** [Constellation/ibrik#27]
Istanbul has `/* istanbul ignore next */`. Whats the ibrik way of doing it? Or is that even supported?

**Comment by michaelficarra** [comment]
Does `### istanbul ignore next ###` not work?

**Comment by eddiemonge** [comment]
Doesn't seem to.

**Comment by Spadavecchia** [comment]
I tried backtick javascript comment and it doesn't work:
`/* istanbul ignore next */`

**Comment by jigfox** [comment]
Any new on this?

**Comment by rktjmp** [comment]
+1

**Comment by Zolmeister** [comment]
+1

**Comment by kimardenmiller** [comment]
@Constellation any idea when this fix will make it into the NPM release?

**Comment by Spadavecchia** [comment]
Why not published yet? How can I help?

**Comment by kimardenmiller** [comment]
Thanks, @Spadavecchia. It's not in 2.0, correct? ... https://www.npmjs.com/package/ibrik

**Comment by Spadavecchia** [comment]
@kimardenmiller It's not in 2.0 Who can publish it?
